### ISSUE TITLE
Yoda challenge e iat.py fix.py

### ISSUE THREAD

**Issue by xiaoyaod** [0xeb/allthingsida#1]
Your work is great. Do you have plans to release other files like iat.py fix.py? If not, can you explain the idea and python libraries used? Yoda challenge

**Comment by 0xeb** [comment]
There is no really IAT fixing. That's just a decompiler action: "Decompile as". What we need to figure out is the hashes and what API they relate to.

**Comment by 0xeb** [comment]
Follow Issue #2
